baseURL: 'https://w.jiezi.cc/'
title: JeiZi
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: 'A fast, clean Hugo theme'
homepage: 'https://w.jiezi.cc/'
defaultContentLanguage: 'zh'
#googleAnalytics: G-7E4JNTL3ES
enableRobotsTXT: true
paginate: 10
hasCJKLanguage: true
copyright: "2023 GuangzhengLi All rights reserved"
Author:
  name: "JeiZi"
  email: "@gmail.com"
params:
  brand: HOME
  avatarURL: /images/avatar.png
  author: Hugo Ladder
  authorDescription: A clean, fast hugo theme focused on Reading
  info: Build a free and beautiful blog site to record your thoughts and increase your influence
  favicon: /images/avatar.ico
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: data-dark-mode

  guestbook:
    title: Guestbook
    description: Leave a comment below. It could be anything – appreciation, information, wisdom, or even humor. Surprise me!!!

languages:
  zh:
    languageName: 中文
    author: Ladder 主题
    authorDescription: 一个美观，快速并且专注于阅读的主题
    info: 帮助开发者构建一个免费并且漂亮的博客网站，记录自己的思考并且提高自己的影响力
    guestbook:
      title: 留言板
      description: 您的评论，会让该网站更精彩！
    menu:
      main:
        - name: 文章
          url: /blog
          weight: 1
        - name: 生活
          url: /art
          weight: 2
        - name: 标签
          url: /tags
          weight: 3
        - name: 历史
          url: /archives
          weight: 3
        - name: 留言板
          url: /guestbook
          weight: 4
        - name: 关于
          url: /about
          weight: 5
   
taxonomies:
  series: series
  tag: tags
